# Generated by Django 5.2.9 on 2025-12-03 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='foto',
        ),
    ]
